/**
 * A type of hit object which explicitly specifies whether it should generate ticks.
 */
export interface IHasGenerateTicks {
  /**
   * Whether or not slider ticks should be generated by this object.
   * This exists for backwards compatibility with maps that abuse 
   * NaN slider velocity behavior on osu!stable (e.g. /b/2628991).
   */
  generateTicks: boolean;
}
