import { IHitObject } from './IHitObject';
import { IHasPath } from './Types/IHasPath';
import { IHasSliderVelocity } from './Types/IHasSliderVelocity';

export interface ISlidableObject extends IHitObject, IHasPath, IHasSliderVelocity {
  /**
   * Spacing between ticks of a slidable object.
   */
  tickDistance?: number;

  /**
   * The length (in milliseconds) between ticks of this slidable object.
   */
  tickInterval?: number;

  /**
   * An extra multiplier that affects the number of ticks 
   * generated by this slidable object.
   * An increase in this value increases tick distance, 
   * which reduces the number of ticks generated.
   */
  tickRate?: number;

  /**
   * Velocity of a slidable object.
   */
  velocity: number;
}
