import { IHitObject } from './IHitObject';
import { IHasLegacyLastTickOffset } from './Types/IHasLegacyLastTickOffset';
import { IHasPathWithRepeats } from './Types/IHasPathWithRepeats';
import { IHasVelocity } from './Types/IHasVelocity';

// TODO: Not every slidable object has legacy last tick offset, velocity or repeats.
export interface ISlidableObject extends
  IHasPathWithRepeats,
  IHitObject,
  IHasLegacyLastTickOffset,
  IHasVelocity
{
  /**
   * Spacing between ticks of a slidable object.
   */
  tickDistance?: number;

  /**
   * The length (in milliseconds) between ticks of this slidable object.
   */
  tickInterval?: number;

  /**
   * An extra multiplier that affects the number of ticks 
   * generated by this slidable object.
   * An increase in this value increases tick distance, 
   * which reduces the number of ticks generated.
   */
  tickRate?: number;
}
